### ISSUE TITLE
Auth with SSO - fields 'discoverable_by_name' and 'discoverable_by_email'

### ISSUE THREAD

**Issue by abonanni** [go-vikunja/api#107]
### Description

The fields 'discoverable_by_email' and 'discoverable_by_name' are resetted to 0 in the databases when a user log in whit SSO.

And we have the same issue with 'frontend_settings' field.

### Vikunja Frontend Version

0.22.0

### Vikunja API Version

0.22.0

### Browser and version

FF 122

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
Are you able to reproduce this with the latest unstable build?

**Comment by Spiritreader** [comment]
Fixed for me with:

Frontend Version: 0.22.0+89-30d599369f

API Version: v0.22.0+32-d38050f2b8
