### ISSUE TITLE
 Error Request failed with status code 500 Internal Server Error

### ISSUE THREAD

**Issue by Shardonnay** [go-vikunja/api#14]
Hello, beforehand I want to thank you for this amazing project !
I'm not sure if this error is really a bug or just a simple permission error.

The problem:
When uploading an attachment or setting a wallpaper I get the following error message: " Error Request failed with status code 500 Internal Server Error". In the docker container log I got the following error message: "ERROR	▶ handler/UploadBackground 1f7 open files/3: permission denied"

My docker compose file looks like the following:
version: '3'

services:
  api:
    image: vikunja/api
    environment:
      VIKUNJA_DATABASE_TYPE: sqlite
      VIKUNJA_SERVICE_FRONTENDURL: URL
      VIKUNJA_SERVICE_ENABLETASKATTACHMENTS: 1
      VIKUNJA_SERVICE_ENABLEREGISTRATION: 1
      VIKUNJA_SERVICE_ENABLELINKSHARING: 1
      VIKUNJA_SERVICE_ENABLETASKCOMMENTS: 1
      VIKUNJA_SERVICE_ENABLEEMAILREMINDERS: 1
      VIKUNJA_SERVICE_ENABLEUSERDELETION: 1
      VIKUNJA_MAILER_ENABLED: 1
      VIKUNJA_MAILER_HOST: SERVER
      VIKUNJA_MAILER_PORT: 587
      VIKUNJA_MAILER_USERNAME: EMAIL
      VIKUNJA_MAILER_PASSWORD: PASSWORD
      VIKUNJA_RATELIMIT_ENABLED: 0
      VIKUNJA_FILES_MAXSIZE: 8000MB
      VIKUNJA_SERVICE_ENABLETOTP: 1
      VIKUNJA_SERVICE_TIMEZONE: Europe/Berlin
    ports:
      - 3456:3456
    volumes:
      - ./files:/app/vikunja/files
    restart: unless-stopped
  frontend:
    image: vikunja/frontend
    ports:
      - 4242:80
    environment:
      VIKUNJA_API_URL: URL/api/v1
    restart: unless-stopped

**Comment by kolaente** [comment]
Hi!

That looks a lot like a permission issue.

Vikunja runs as the user 1000:1000 in the container so that user needs to have access to the mounted files folder. Check out this forum thread about the problem: https://community.vikunja.io/t/permission-error-uploading-attachment/425

**Comment by Shardonnay** [comment]
Thanks @kolaente ! I will now close the issue.
