### ISSUE TITLE
Repeating interval disappears when task is postponed several times

### ISSUE THREAD

**Issue by svigneau** [go-vikunja/api#15]
When tasks with a repeating interval are postponed several (~3) times, the repeating interval settings are lost. I am using the latest Vijunja version (0.18.2) on Cloudron.

**Comment by kolaente** [comment]
I assume you are talking about the "defer due date" functionality?

Can you reproduce this on [try](https://try.vikunja.io)?

**Comment by kolaente** [comment]
I was not able to reproduce this. Please ping if you manage to reproduce it on [try](https://try.vikunja.io).
