### ISSUE TITLE
Due time is reset when due day is changed

### ISSUE THREAD

**Issue by svigneau** [go-vikunja/api#16]
When changing the due day of a task, the due time is automatically reset (typically to 12 pm) instead of remaining as previously set. It would be more natural if the due day could be changed without affecting the due time. A user case would be someone trying to reschedule a task due today in the evening (say 7 pm) to another day at the same time in the evening (7 pm). I am using the latest Vijunja version (0.18.2) on Cloudron.

**Comment by kolaente** [comment]
Fixed in https://kolaente.dev/vikunja/frontend/pulls/1336 - please check with the next unstable build once the CI released it. (should take ~30min).

Closing this as resolved, feel free to ping if you have other issues or questions.
