### ISSUE TITLE
Due hour is not changed until the curser moves to another field

### ISSUE THREAD

**Issue by svigneau** [go-vikunja/api#17]
When trying to change the due time of a task, changing the value of the due time and pressing on "confirm" doesn't produce any change. Instead, the following steps need to be taken: 1) change the due time, 2) move the cursor to another field, 3) press "confirm". The same issue exists when changing minutes. I am using the latest Vijunja version (0.18.2) on Cloudron.

**Comment by mtettke123** [comment]
Bug is still open with try/unstable.

**Comment by dpschen** [comment]
@kolaente: this seems to be solved
