### ISSUE TITLE
Cannot Specify Non-Default List when Creating Item

### ISSUE THREAD

**Issue by conor-f** [go-vikunja/api#24]
This is a pretty annoying bug that has started happening to me recently. I can provide any additional information/test things for debugging if you let me know what to do! I run Vikunja with docker-compose behind Traefik on a home server. I ran `docker pull vikunja/frontend` and `docker pull vikunja/api` to get the newest `latest`. The frontend tells me:

```
Frontend Version: 0.18.2

API Version: v0.18.1
```

The issue I'm seeing is whenever I specify a list when creating an item, the item doesn't go to that list and just gets added to the default list regardless. e.g. If list `A` is my default list and `B` is another list, and I create the item `Do this #B` it will just add the item `Do this` to list `A` and nothing to list `B`. Other "Quick Add Magic" works fine (e.g. specifying the time) but this aspect does not.

**Comment by kolaente** [comment]
Can you reproduce this on [try](https://try.vikunja.io)?

**Comment by conor-f** [comment]
I actually get different behaviour on try. It only adds to the default list but also doesn't remove the `#otherListName` which it does on my local instance

**Comment by kolaente** [comment]
Mhh sounds like this was fixed in the meantime but not backported to stable.

Does it make a difference if you set the quick add magic mode to Todoist or Vikunja?

Try runs the last unstable version, `latest` is the last stable release.

**Comment by conor-f** [comment]
Nope makes no difference to me what magic mode is being used, I'd just like the feature of putting items in different lists from the one input box!

Is it relatively safe to run `try` locally? From looking at the docker hub it's under the tag `unstable`?

**Comment by kolaente** [comment]
This really looks like a bug, I'll take a closer look.

> Is it relatively safe to run try locally? From looking at the docker hub it's under the tag unstable?

Well it's bleeding edge so there's a few bugs here and there. From using it on my own instance I'd say it is definitely usable though.

**Comment by kolaente** [comment]
Tried to reproduce this but it works without issues. Here's a video recording of it:

https://user-images.githubusercontent.com/13721712/161382732-feb44768-629a-4036-94bf-5e3fc675e11f.mp4

What exactly does not work when you use it? Can you provide clear steps to reproduce? Can you provide a recording of the bug?

**Comment by conor-f** [comment]
Sorry about this, quite a stupid mistake :(

It seems from your video that the correct syntax for specifying the list is to use `+` instead of `#`. From the help, I saw:

> Assignees
To directly assign the task to a user, add their username prefixed with + to the task. You can use this multiple times.
> 
> List
To set a list for the task to appear in, enter its name prefixed with #. This will return an error if the list does not exist.

So maybe the fix is to just update the docs?

**Comment by kolaente** [comment]
The symbol used depends on the selected quick add magic mode. In the vikunja mode it is a + for lists, in the todoist mode it is a #. The docs change when the mode is changed in the settings.

**Comment by conor-f** [comment]
Sorry, I am no longer on the stable version of Vikunja so can't record a video to reproduce. I see the docs change when you change the magic mode on try.vikunja.io so I suppose this is all moot and any issue I was having will be fixed when the next release is cut to stable :)
