### ISSUE TITLE
Update NGINX Proxy Manager Documentation

### ISSUE THREAD

**Issue by CorneliousJD** [go-vikunja/api#29]
https://vikunja.io/docs/reverse-proxy/#nginx-proxy-manager-npm

This doc is outdated. 

You no longer have console into the container and edit the config, you can do it all via the GUI.

Here's an example -- can replace api with IP of the api service if it has one set.

![image](https://user-images.githubusercontent.com/724777/169339599-9cbe8a84-4281-44b8-b02f-027557b638fc.png)

**Comment by kolaente** [comment]
Would you mind sending a PR to fix it? I don't personally use NPM so I can't really add screenshots or other things for it.

Here's the file: https://github.com/go-vikunja/api/blob/main/docs/content/doc/setup/reverse-proxies.md

**Comment by CorneliousJD** [comment]
sure thing, done! I'll let you review and merge as you see fit :)
