### ISSUE TITLE
Task URL for reminders

### ISSUE THREAD

**Issue by vitobotta** [go-vikunja/api#3]
Hi! I am testing Vikunja and I really like it! How do I configure the URLs for tasks in email notifications? They don't include the domain. I have tried setting the variable VIKUNJA_FRONTEND_URL but it seems to be ignored. Thanks!

**Comment by kolaente** [comment]
Hi there!

Try `VIKUNJA_SERVICE_FRONTENDURL` instead. [More info here](https://vikunja.io/docs/config-options/#frontendurl).

**Comment by vitobotta** [comment]
That worked, thanks!
