### ISSUE TITLE
Adding start date automatically adds the end date causing sync error

### ISSUE THREAD

**Issue by mzfr** [go-vikunja/api#33]
So I'm not sure why this was added but if I add "Start date" to the task then "end date" is added.

Now it would have been fine, but I noticed that if a task has an "End date" property, Davx^5 App throws an error stating "received an invalid task from server". When I removed that property it was able to sync fine.

**Comment by kolaente** [comment]
Should be fixed in https://github.com/go-vikunja/api/commit/2b074c60a736d5ac30d14ef03c1e0e251454473b - please check with the next unstable build in ~30 min if it fixes your issue.
