### ISSUE TITLE
CalDAV: Times have offset of timezone

### ISSUE THREAD

**Issue by mtettke123** [go-vikunja/api#36]
There seems to be a small bug when syncing times via CalDAV:
Date/Time in App (Tasks.org)
![index](https://user-images.githubusercontent.com/82048170/178934463-c7317922-e338-41c5-84c7-0da147690835.jpg)

Date/Time Synced to Vikunja:
![grafik](https://user-images.githubusercontent.com/82048170/178934604-ea78659e-fe2b-44ca-87c1-90583b6c6671.png)

Timezone:
![grafik](https://user-images.githubusercontent.com/82048170/178934691-af5ee58c-dd58-4724-9a7d-4c75962563a7.png)

The offset seems to be exactly the timezone...

**Comment by theryxs** [comment]
Vikunja uses 'GMT' as default timezone if none is configured. 
https://vikunja.io/docs/config-options/#timezone

Setting the environment variable to CET for Europe/Berlin worked for me.

**Comment by mtettke123** [comment]
Doesn't work for me. Changed 
      VIKUNJA_SERVICE_TIMEZONE: "Europe/Berlin"
to
      VIKUNJA_SERVICE_TIMEZONE: "CET"
- no changes.

Even tried without VIKUNJA_SERVICE_TIMEZONE being set - same result.

**Comment by kolaente** [comment]
Vikunja returns all time zones in utc. It should be the responsibility of the client to adjust it based on the time configured on the client.

 The time zone in VIkunja's settings is only used to handle reminders and other transactional emails.

**Comment by mtettke123** [comment]
Is the Timezone setting in Vikunja used by the Frontend to adjust the time? It's so strange: If I send a due date via CalDAV it's off by 2 hours in Vikunja web regardlessly if the timezone ist set... And it doesn't seem to matter if I change the setting in the docker-compose file or in the vikunja web interface in settings...

**Comment by kolaente** [comment]
> Is the Timezone setting in Vikunja used by the Frontend to adjust the time?

It's not. That depends on your browser.

**Comment by bfly75** [comment]
> Vikunja returns all time zones in utc. It should be the responsibility of the client to adjust it based on the time configured on the client.

the date-times in the VTODO object obtained from Vikunja's CalDav seems to 'floating' and not bound to any time zone in particular:
DUE:20221209T144501

If it has to be truely a fixed UTC time, it should end with 'Z' :

DUE:20221209T144501Z

At least the Open-Xchange Caldav server also includes the 'Z'.  

See also: https://icalendar.org/iCalendar-RFC-5545/3-3-5-date-time.html

**Comment by kolaente** [comment]
Changing VIkunja's calDAV output so that it always adds the `Z` suffix to dates is easy, but that does not solve the original problem. Task.org seems to send dates without any time zone attached to them and thus they are assumed to be UTC and saved as such in the db. When opening the task in the browser, it converts the returned utc date to the time zone set in the browser.

**Comment by kolaente** [comment]
I've added the `Z` suffix in c3de15aa892f273ecdc5fb353d65b076c04b95a3. Given the rest seems to be a client limitation, I'll close this issue now.

Don't hesitate to ping if you encounter other problems.
