### ISSUE TITLE
Reminders for repeating tasks

### ISSUE THREAD

**Issue by vitobotta** [go-vikunja/api#4]
Hi! Thanks for this awesome app, I really like it. It seems that it is not possible at the moment to set a reminder for repeating tasks, is that correct? If yes, any plans to add this? It would be awesome. Thanks! :)

**Comment by kolaente** [comment]
Thanks for the kind words!

It is possible to add reminders for repeating tasks as usual. Just click on the "set reminders" button in the task detail view to set them. Or do you have something specific in mind?

**Comment by vitobotta** [comment]
Hi @kolaente ! Thanks for your reply. When I set a reminder for a repeating task, it asks me the date and time. Does it mean that it will send the notification at the same time at the next occurrence?

**Comment by vitobotta** [comment]
Gotcha! Sounds awesome. Thanks!

**Comment by vitobotta** [comment]
Hi @kolaente ! I'm trying this but reminders seem to work only for the first occurrence of a repeating task. Maybe I am missing something obvious but what I do is

- set a repeating interval, like every day
- set a reminder starting say tomorrow at 10am

If I understood correctly from your previous message, after the first occurrence it should increase the date/time of the reminder by 1 day, meaning that I should see a new email reminder after 1 day at 10am. Is this correct or am I misunderstanding how it works? Thanks!

**Comment by kolaente** [comment]
Have you marked the task as done? It will only increase the dates after that.

**Comment by vitobotta** [comment]
Hi! Yes, I have. The reminder remains in red, it's not updated.

**Comment by vitobotta** [comment]
Uhm does this work only if the due date is set?

**Comment by vitobotta** [comment]
Uhm just to see what happens, I clicked the checkbox for the same task but this time from the list, and the reminder went back to red with yesterday's date/time. Is this expected?

**Comment by kolaente** [comment]
> Uhm just to see what happens, I clicked the checkbox for the same task but this time from the list, and the reminder went back to red with yesterday's date/time. Is this expected?

That's not expected. Is that reproducable on [try](https://try.vikunja.io/)?

**Comment by vitobotta** [comment]
Ok so if I click on the "Done!" button on the task's page, it appears to update the reminder's date/time but if I just refresh the page, the reminder is back to red with the old date/time, indicating that it wasn't actually updated. 

Yes, I see the same on the demo app. It shows the reminder as updated in the UI, but refreshing the page shows the old date/time for it

**Comment by vitobotta** [comment]
See task https://try.vikunja.io/tasks/943 - it shows the new date/time for the reminder when I click "Done!" but refreshing shows the old date/time

**Comment by kolaente** [comment]
Okay that's definitely a bug. I'll take a look

**Comment by vitobotta** [comment]
Thanks for confirming that it's not just something I did wrong :D

**Comment by kolaente** [comment]
Fixed in 483496cc260a4324c49e6738eda491d01fadb2c0. The CI is currently releasing a new unstable release (lands on try in a bit) which should be ready in ~30min, please check if the error persists with that.

**Comment by vitobotta** [comment]
@kolaente Awesome, will try it right away, thanks!

**Comment by vitobotta** [comment]
Perfect, it looks like it does update the reminders now. Awesome stuff, thanks again!

**Comment by kolaente** [comment]
Glad it works, you're welcome!
