### ISSUE TITLE
Dark Color Scheme, wrong color on username

### ISSUE THREAD

**Issue by mariushosting** [go-vikunja/api#41]
When change the Vikunja to Dark Color Scheme the username at the top right of the page should be white not dark grey.
I honestly can't read my username when switch to Dark Color Scheme.

![Screenshot 2022-08-12 12 17 08 - Copy](https://user-images.githubusercontent.com/37554361/184325343-ed0149a0-57fc-4dac-a2b6-14602b89a326.png)

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/frontend/commit/3ab58a015cd66c63cd79839c7634e3e28aa52140.

Please check with the next unstable release if it fixes your issue.
