### ISSUE TITLE
Easier way to add subtasks

### ISSUE THREAD

**Issue by AlvinVrolijk** [go-vikunja/api#43]
I find it kind of hard to add completely new subtasks, maybe a new easier way to do so?

**Comment by kolaente** [comment]
What's hard about it?

**Comment by AlvinVrolijk** [comment]
Well, too much clicks. I'd like for instance Trello's way of adding subtasks, with Vikunja you need to click add relation, then select subtask, then create the subtask... seems to me like not easyMet vriendelijke groet,Alvin VrolijkOn 13 Aug 2022, at 8:31 AM, kolaente ***@***.***> wrote:﻿
What's hard about it?

**Comment by kolaente** [comment]
Are you looking for checklists?

https://community.vikunja.io/t/task-checklists/680

**Comment by AlvinVrolijk** [comment]
Yeah, something like that. But that you CAN assign the subtasks to person's as well. So still Vikunja's type of subtasks but with a checklist user interface?Met vriendelijke groet,Alvin VrolijkOn 13 Aug 2022, at 11:43 PM, kolaente ***@***.***> wrote:﻿
Are you looking for checklists?
https://community.vikunja.io/t/task-checklists/680

**Comment by kolaente** [comment]
If there was a shortcut which would open the task relation option with subtask pre-selected and focused on the input?

**Comment by AlvinVrolijk** [comment]
Sure ig!Met vriendelijke groet,Alvin VrolijkOn 15 Aug 2022, at 4:57 PM, kolaente ***@***.***> wrote:﻿
If there was a shortcut which would open the task relation option with subtask pre-selected and focused on the input?

**Comment by dpschen** [comment]
I think this was solved by https://kolaente.dev/vikunja/frontend/pulls/2443

**Comment by alifen88** [comment]
> If there was a shortcut which would open the task relation option with subtask pre-selected and focused on the input?

This ^^ absolutely hits the nail on the head for me. The click and scroll gets fatiguing quickly when adding a lot of subtasks. Something like is mocked-up below (penultimate line) is how I imagine it...

![image](https://user-images.githubusercontent.com/20014843/197592747-c33aa371-0a1f-405a-b07c-094722b67fd8.png)

**Comment by kolaente** [comment]
@alifen88 Do you want to send a PR?
