### ISSUE TITLE
Categorize all task detail actions

### ISSUE THREAD

**Issue by AlvinVrolijk** [go-vikunja/api#44]
Categorize all actions that can be taking when detailed viewing a task

**Comment by kolaente** [comment]
What do you mean by that? Categorize how?

**Comment by AlvinVrolijk** [comment]
Like maybe sort some actions into a small header for the kind of actions, for instance the basic ones like labeling, assigning etc at the top with no header.. Then a header for like ..., and then also the Extra stuff like relations and that kind of stuff.

**Comment by kolaente** [comment]
Implemented in 3bb5308141112fd215144ef2bc33a3d213b108af
