### ISSUE TITLE
Switch sorting of due days for Homepage

### ISSUE THREAD

**Issue by AlvinVrolijk** [go-vikunja/api#45]
Maybe make the Current Tasks overview that the most soon due tasks are on top of the page, going till the furthest away.

**Comment by kolaente** [comment]
But that's already the case?

**Comment by AlvinVrolijk** [comment]
Right now it sorts from most far away due, to to the bottom with nearest due dates + no due dates:
https://imgur.com/a/rGrLpfS

**Comment by kolaente** [comment]
The latest version has it correctly. What version are you using?

![image](https://user-images.githubusercontent.com/13721712/184511650-5bcc8f89-6a6f-433c-8e88-69410207a632.png)

(tested on [try](https://try.vikunja.io))

Please upgrade.

**Comment by AlvinVrolijk** [comment]
Latest from DockerHubMet vriendelijke groet,Alvin VrolijkOn 13 Aug 2022, at 11:42 PM, kolaente ***@***.***> wrote:﻿
The latest version has it correctly. What version are you using?

(tested on try)
Please upgrade.

**Comment by kolaente** [comment]
And which version is reported in the "about" tab from the user menu?

**Comment by AlvinVrolijk** [comment]
0.19.0, both frontend and APIMet vriendelijke groet,Alvin VrolijkOn 14 Aug 2022, at 8:31 AM, kolaente ***@***.***> wrote:﻿
And which version is reported in the "about" tab from the user menu?

**Comment by kolaente** [comment]
Can you send a screenshot?

Can you reproduce this on try? https://try.vikunja.io
