### ISSUE TITLE
Error while building the main branch using the provided Dockerfile

### ISSUE THREAD

**Issue by alexcustos** [go-vikunja/api#5]
There are no issues with the latest tag v0.17.1, but the same Dockerfile will exit with an error in `mage build:clean build`. Even with the `--debug` flag enabled, there's no clue what's going wrong. The output is the same until the error occurs.

**Comment by kolaente** [comment]
What commit are you trying this on? Works fine for me with the latest (https://github.com/go-vikunja/api/commit/dcddaab7b58ab2e03e0d0f3f0b771a1e6ec0dbce). The CI run of it was successful too.

**Comment by alexcustos** [comment]
Thank you, I found that /pkg/modules/auth/openid/providers.go was not properly merged for some reason.
