### ISSUE TITLE
Duplicate numbering when moving tasks between lists

### ISSUE THREAD

**Issue by kattelk** [go-vikunja/api#52]
### Description

When moving tasks between lists, the numbering in the Table view seems to create duplicate task numbers.  To recreate this problem:
	- Create two lists.  Create Task A in List 1. Create Task B in List 2. Move Task A to List 2.  
	- Now create Task C in List 2,. Looking at the Table for List 2, and sorting by #, we have:  
		  #2 Task A
		  #1 Task B
		  #2 Task C
	- I would have expected  
		  #1 Task B
		  #2 Task A
		  #3 Task C
As far as I can tell this duplicate numbering only occurs once per list.

### Vikunja Frontend Version

0.19.1+463-4ad99bdad1

### Vikunja API Version

0.19.2+95-7b77974b03

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/api/commit/c4950964443a9bffc4cdd8fc25004ad951520f20 - please check with the next unstable build if the problem really went away.
