### ISSUE TITLE
migrate error with database connect string

### ISSUE THREAD

**Issue by Freundschaft** [go-vikunja/api#54]
### Description

after upgrading from 0.19 to 0.20 vikunja-api doesnt start anymore with the following error:

2022-11-09T14:12:46.21822349Z: CRITICAL ▶ migration/initMigration 001 Could not connect to db: parse "postgres://vikunja:password@1.1.1.1:5432/vikunja?sslmode=disable&sslcert=&sslkey=&sslrootcert=": invalid port ":password" after host

It seems that something with the parsing mechanism during migration doesnt work properly.

### Vikunja Frontend Version

0.20

### Vikunja API Version

0.20

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
How are you hosting Vikunja? Do you have special characters in the host name, username or password?

**Comment by Freundschaft** [comment]
yes, Im using this helm chart, https://artifacthub.io/packages/helm/k8s-at-home/vikunja/2.3.0
and Im using special characters in the password,
host name is an ip address, username is without special characters.

**Comment by kolaente** [comment]
Does it work with the unstable version of the api?

**Comment by Freundschaft** [comment]
i just tried:

so its

0.19: works
0.20 doesnt work
unstable: works

**Comment by kolaente** [comment]
Then it's already fixed and will be included with the next release.
