### ISSUE TITLE
Kanban reset when syncing with CalDAV

### ISSUE THREAD

**Issue by kattelk** [go-vikunja/api#56]
### Description

When syncing lists from Vikunja to CalDAV, all tasks in the Kanban view move to the Backlog list.

On both my own system and the demo system, it occurred the first time Vikunja was connected to CalDAV.  Seems to occur less often as I continue testing.

### Vikunja Frontend Version

0.20.2+3-f152a84847

### Vikunja API Version

v0.20.1+34-6a97a214a3

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
Does this happen with all tasks or only those who are updated?

**Comment by kattelk** [comment]
It is not just the updated tasks. I can't consistently get this phenomenon to occur after the first sync, but it can (and does often) occur when new tasks are added and synced, and when the frontend is not showing the kanban view (showing the kanban view seems to "protect" it during the sync).

**Comment by kolaente** [comment]
So this does only affect new tasks?

> and when the frontend is not showing the kanban view (showing the kanban view seems to "protect" it during the sync).

This should not make any difference.

**Comment by kattelk** [comment]
No, it does not only affect the new tasks, but it seems to only affect lists where there are new tasks.

**Comment by kolaente** [comment]
Should be fixed in https://github.com/go-vikunja/api/commit/194b88e2ebd0d36dc525154a2ca2e8462f47e149 - please check with the next unstable build once it's ready.
