### ISSUE TITLE
Repeating character of tasks is not synced to CalDAV

### ISSUE THREAD

**Issue by kattelk** [go-vikunja/api#57]
### Description

Repeating events in Vikunja are shown as single occurrence events in Tasks.org when synced to CalDAV.  I am not sure if this is a problem with Vikunja or Tasks.org.

### Vikunja Frontend Version

0.20.2+3-f152a84847

### Vikunja API Version

v0.20.1+34-6a97a214a3

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
Since the repeating schedule is saved with the task there is only one task. IIRC it is the responsibility of the clients to show them multiple times.

Do you have an example of other services which do this?

**Comment by kattelk** [comment]
Tasks.org seems to be able to deal with its own repeating tasks which are created in Tasks.org. I do not currently have access to another client which supports repeating tasks.

**Comment by kolaente** [comment]
Looks like this was not implemented in Vikunja, I've added it in https://github.com/go-vikunja/api/commit/c5327845ee54ec908483a9de8007c5c570abe627. Please check with the next unstable build (~1h) once [the ci built it](https://drone.kolaente.de/vikunja/api/4542) to see if this works properly.
