### ISSUE TITLE
TickTick import fails with error code 500

### ISSUE THREAD

**Issue by JoelB** [go-vikunja/api#61]
### Description

When I try to import my TickTick backup CSV file, the upload fails with "Request failed with status code 500 Internal Server Error"

When I check the logs of the API server, this is the error:
2023-01-22T03:20:20.330785492Z: ERROR	▶ handler/Migrate 0bf strconv.Atoi: parsing "": invalid syntax

I'm assuming it's looking for an integer on a certain field and the field is empty, but I cannot tell which field that might be. I tried setting log.level to DEBUG, there isn't any additional detail in the logs.

Is there any way to determine what field it is failing on?

In case it matters, I am running Vikunja on Podman using my own Nginx reverse proxy.

Thanks!

### Vikunja Frontend Version

0.20.2

### Vikunja API Version

0.20.1

### Browser and version

Firefox 109

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
There's actually a PR already for this: https://kolaente.dev/vikunja/api/pulls/1356

**Comment by kolaente** [comment]
Should be fixed in https://github.com/go-vikunja/api/commit/31a1452839353e7c47f8402904210c53d6856e93. Please check out the next unstable build or on [try](https://try.vikunja.io).
