### ISSUE TITLE
Repeating task doesn't get done from summary page

### ISSUE THREAD

**Issue by adezxc** [go-vikunja/api#62]
### Description

If you create a task with the query `every day Task`. When you press done, it just unmarks it as done, probably because it is repeating. The task should probably be hidden until the next day if it was checked as done.

### Vikunja Frontend Version

3dfb8b858ecb4bf1d8a3be9b8837445086991631 (latest)

### Vikunja API Version

87c2e442f2d48f540c7a9a97630a2c4d211e760f (latest)

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by dpschen** [comment]
I'm not sure what page you mean by 'summary page'? Could you write a step by step reproduction?

**Comment by adezxc** [comment]
Okay, so this isn't a bug since I forgot to use the Due Date function and it works now, I just thought it wouldn't work the right way while writing this report. Closing this.
