### ISSUE TITLE
Bug: Docker instance using default compose template - Error message on web page on first login

### ISSUE THREAD

**Issue by jamess60** [go-vikunja/api#75]
### Description

Hi 

I have just spun up a docker instance of Vikunja using the compose example (without any reverse proxy) - see [here](https://vikunja.io/docs/full-docker-example/)

When logging in for the first time, I get the following error:
An error occurred: AxiosError: Network Error Please check if the api url is correct.

The logs for the DB and FE containers look fine, but this is the output of the API container:

info: creating the new user vikunja with 1000:1000
usermod: no changes
2023/07/06 19:49:07 No config file found, using default or config from environment variables.
2023-07-06T19:49:07.351882121Z: CRITICAL	▶ migration/Migrate 002 Migration failed: dial tcp: lookup db on 127.0.0.11:53: no such host
^ Infinite loop of these lines 

### Vikunja Frontend Version

docker:latest

### Vikunja API Version

docker:latest

### Browser and version

Firefox Developer Edition 116.0b1 macOS

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

![Screenshot 2023-07-06 at 21 55 11](https://github.com/go-vikunja/api/assets/126415249/141afded-75da-47eb-8481-bb246b0c60c4)

**Comment by kolaente** [comment]
>  2023-07-06T19:49:07.351882121Z: CRITICAL arrow_forward migration/Migrate 002 Migration failed: dial tcp: lookup db on 127.0.0.11:53: no such host

That means your config can't reach the database? Did you use the compose file verbantim?

**Comment by jamess60** [comment]
Hi

Changes made to the default:
- Added "vikunja-" to each service name (and updated the api depends on to reflect the new name)
- Updated VIKUNJA_API_URL to the IP of the host (as the instructions state)
- DB password (its the same in API and DB so should be ok) 
- Host side of the volume path 

I didnt make any changes that would cause issues as far as I can tell

My compose exert can be found in this pastebin, the password is github123, there is no expiration date
https://pastebin.com/d30P37NZ

**Comment by kolaente** [comment]
> Added "vikunja-" to each service name (and updated the api depends on to reflect the new name)

That changes the name of the database service. You need to adjust the value of `VIKUNJA_DATABASE_HOST` in the api config.

**Comment by kolaente** [comment]
Why did you prefix the name? Compose does that automatically?

**Comment by jamess60** [comment]
Good spot - layer 8 issue afterall! Thank you so much - I do apologise!

I changed it because docker changed the prefix to the directory name the compose file was in which wasnt ideal for me.

**Comment by kolaente** [comment]
Glad to hear it's solved now!

> I changed it because docker changed the prefix to the directory name the compose file was in which wasnt ideal for me.

You can change that with the `COMPOSE_PROJECT_NAME` environment variable. It only has to be set in your shell, but you can also put it in a `.env` file and docker compose will read and pick that up.

**Comment by jamess60** [comment]
Sweet - thanks for the tip!

Noticed it even supports 2FA, must say this is a really polished and well thought out tool, thanks guys! Good effort

**Comment by KalyaSc** [comment]
Solved also my issue ! Thanks for your beautiful piece of software !
