### ISSUE TITLE
Lists did not get renamed to projects, all tasks are gone

### ISSUE THREAD

**Issue by verymilan** [go-vikunja/api#77]
### Description

Hi there, i've just updated to .21 – it appears that the migration did not work as expected and my account now looks very empty. :(
I have not seen relevant logoutput regarding this very problem yet.

### Vikunja Frontend Version

0.21.0

### Vikunja API Version

0.21.0

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by verymilan** [comment]
argh, my bad! sorry about that!

**Comment by kolaente** [comment]
What was the problem?

**Comment by verymilan** [comment]
Huh, reply by mail didn't work:

I somehow managed to put the binary in the wrong bin folder, following my shellhistory, and the service does a full path to the binary 🙈
