### ISSUE TITLE
Unable to include nested projects in Saved Filter

### ISSUE THREAD

**Issue by perfectra1n** [go-vikunja/api#82]
### Description

When there are nested projects like so:
![image](https://github.com/go-vikunja/frontend/assets/2390633/bf2a51e1-588b-470d-bb1e-1bb63a4bca41)

Sometimes I'm unable to see the projects in the `projects.list` view, in the Saved Filter:
![image](https://github.com/go-vikunja/frontend/assets/2390633/188aa0c3-acd5-491a-b19e-800b5331c310)

But other times I do? I'm not sure how to diagnose why sometimes I can see nested projects and other times I can't... these are older projects, perhaps from some migrations ago?

### Vikunja Frontend Version

v0.21.0

### Vikunja API Version

v0.21.0

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
Looks like the search only returns projects with no parent and ignores all which do have a parent.

**Comment by perfectra1n** [comment]
I meant to open this up in the frontend repo, my bad. Thanks for transferring it :)

**Comment by kolaente** [comment]
No worries, it's not always clear which part of Vikunja is responsible for a bug :)
