### ISSUE TITLE
Cannot delete users from cli

### ISSUE THREAD

**Issue by KaibutsuX** [go-vikunja/api#85]
### Description

```
sudo vikunja user delete --now ID
2023/10/03 16:49:44 Using config file: /opt/vikunja/config.yml
2023-10-03T16:49:44.854910447-04:00: INFO	▶ migration/Migrate 052 Ran all migrations successfully.
You requested to delete the user immediately. Are you sure?
To confirm, please type "yes, I confirm" in all uppercase:
YES, I CONFIRM
2023-10-03T16:49:48.795307432-04:00: CRITICAL	▶ cmd/func22 0bb Error removing the user: Default project cannot be deleted [ProjectID: 7]
```

I should be able to delete any user regardless of that user's configuration. If I have access to root on the server and the vikunja cli, then user configs should not prevent the admin from admin-ing.

### Vikunja Frontend Version

0.21.0

### Vikunja API Version

0.21.0

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
This has already been fixed in acb03c430ec49867b99249c5d432c4fa482abf35.
