### ISSUE TITLE
Notification Event

### ISSUE THREAD

**Issue by qiandun** [go-vikunja/api#90]
### Description

1. Can enhance the reminder function that allows choose a recurrence time, such as ticktick.com, repeat for a week or a year?
2. It is also possible to add the Chinese lunar calendar <https://github.com/6tail>?

no bug，this‘s a good project

### Vikunja Frontend Version

latest

### Vikunja API Version

latest

### Browser and version

chrome latest

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
There's an item on the roadmap to add more recurrence options, similar to how TickTick does it.

I'm afraid we won't be able to support the Chinese Lunar Calendar in the near future, as that would add a lot of complexit.

**Comment by qiandun** [comment]
All right, thanks
