### ISSUE TITLE
Webhook missing response data (Docker Unstable)

### ISSUE THREAD

**Issue by CyberTechArmor** [go-vikunja/api#98]
### Description

Environment: Docker
Frontend tag: unstable
API tag: unstable
Addition consideration: n8n and the Vikunja n8n community node

I updated to the unstable version to add the webhook functionality. I'm using n8n to test and connect the api integration. I was successfully able to create a webhook and trigger it.

Issue: the response data is empty, both params and query. I'm assuming that the triggered even should pass along some information, even if it's only the id of the event. The specific trigger: task.comment.created.

I attached the n8n response output image for reference. I did not see any other information from either the website or api docs (on the main website or my instance) other than creating/updating, meaning I did not find what the expected response output of a webhook should be (why I added to issues).

*Side note: Vikunja is an awesome project. It's incredibly fast, simple in design but extensive in its capabilities, consistent development and even integrations (like n8n). Just wanted express my appreciation, thank you for the hard work and dedication.

### Vikunja Frontend Version

unstable

### Vikunja API Version

unstable

### Browser and version

Chrome Version 119.0.6045.200 (Official Build) (64-bit)

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

![image](https://github.com/go-vikunja/api/assets/63061216/7df9bb9f-74cb-45a5-8491-26a160aa5d59)

**Comment by kolaente** [comment]
Can you verify if this is a problem of n8n or the Webhook itself? (Adding a webhook for a webhook test provider should do the trick)

**Comment by kolaente** [comment]
It looks like the json header was missing. I've added it in 57bd5aca804b99ef6dcca9178b0f70d3c354ffdc - can you check with the next unstable build if the n8n node works as expected?

**Comment by CyberTechArmor** [comment]
Looks like that resolved the issue:

![image](https://github.com/go-vikunja/api/assets/63061216/359305d6-b79f-4e63-bad7-96e3fe49a5fa)

Thank you for the update.
